User can now click history and segue to history detail
MC3-WIP/monitool pull request #82
Opened 2021-08-20 08:29 UTC by devin1727

2021-08-20 13:16 UTC, chrsomle commented on monitool/Views/iPhone/Components/Tab Items/TodoListTabItem.swift
> +                    .animation(Animation.easeIn)
ini bisa .animation(.easeIn) aja

2021-08-20 13:17 UTC, chrsomle commented on monitool/Views/iPhone/Components/Tab Items/TodoListTabItem.swift
>  		let result = taskViewModel.tasks.filter { $0.status == filter}
swiftlint eyy { $0.status == filter }

2021-08-20 13:18 UTC, chrsomle requested changes
Ada conflict sama file HistoryView.swift di branch dev

2021-08-22 12:53 UTC, devin1727 commented on monitool/Views/iPhone/Components/Tab Items/TodoListTabItem.swift
> +                    .animation(Animation.easeIn)
hoo ini coba coba, animasinya g mau muncul, g tau kenapa

2021-08-22 12:54 UTC, devin1727 commented on monitool/Views/iPhone/Components/Tab Items/TodoListTabItem.swift
>  		let result = taskViewModel.tasks.filter { $0.status == filter}
Ha? maskdunya?

2021-08-23 09:38 UTC, chrsomle approved these changes

2021-08-23 09:38 UTC, merged